name: ark
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.1+1
  # 网络库 https://github.com/flutterchina/dio
  dio: ^3.0.9
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.6
   # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6

  # 启动URL的插件 https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.4.1
  # 图片选择插件 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.3+1
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.19+7
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.2.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # 用于日历功能 https://github.com/apptreesoftware/date_utils
  # date_utils: ^0.1.0+2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.4
    # 曲线图表 https://github.com/aeyrium/bezier-chart
    # bezier_chart: ^1.0.7
    # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.2
    # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0
    # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
    # 状态管理 https://github.com/rrousselGit/provider
  provider: ^4.0.4
    # 高德2D地图插件 https://github.com/simplezhli/flutter_2d_amap
    # flutter_2d_amap:
    #   git:
    #     url: https://github.com/simplezhli/flutter_2d_amap.git
  simple_animations: ^1.3.9
  dotted_border: ^1.0.5
  bip39: ^1.0.3
  circular_check_box: ^1.0.1
  flutter_easyrefresh: ^2.1.0
    # 二维码显示
  qr_flutter: ^3.2.0
  sliding_panel: ^1.0.3
    # 扫码 https://github.com/apptreesoftware/flutter_barcode_reader
  barcode_scan:
    git:
      url: https://github.com/simplezhli/flutter_barcode_reader.git
  # eosRPC and ECC
  eosdart: ^0.4.4
  eosdart_ecc: ^0.4.1
  flutter_secure_storage: ^3.3.1+1
  flutter_launcher_icons: ^0.7.3
  connectivity: ^0.4.4
  pull_to_refresh: ^1.5.6

  event_bus: ^1.1.0
  tree_view: ^0.0.5

  shared_preferences: ^0.5.6
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  lpinyin: ^1.0.9
  # 谁用谁闪亮
  shimmer: ^1.0.0
  # 复杂的网格布局
  flutter_staggered_grid_view: "^0.3.1"
  #官方视频播放器
  video_player: ^0.10.11+1
  open_iconic_flutter: ^0.3.0
#  #第三方播放器
#  chewie: ^0.9.10

  screen: ^0.0.5
  # 腾讯的播放器
#  flutter_tencentplayer:
#    git:
#      url: https://github.com/qq326646683/flutter_tencentplayer.git
  # 图表控件
  syncfusion_flutter_charts: ^18.2.46

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    # 集成测试
  flutter_driver:
    sdk: flutter
  # 单元测试
  test: ^1.9.4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_text.png
    - assets/images/splash_bg.png
    - assets/images/app_icon.png
    - assets/images/main_background.png
    - assets/images/yuyin_white.png
    - assets/images/main_filter.png
    - assets/images/main_search.png
    - assets/images/personal_back_view.png
    - assets/images/logout_avatar.png
    - assets/images/create_user.png
    - assets/images/user_list.png
    - assets/images/upload_img.png
    - assets/images/download.png
    - assets/images/logout.png
    - assets/images/fanhui.png
    - assets/images/ic_desk_normal.png
    - assets/images/ic_mine_normal.png
    - assets/images/ic_desk_selected.png
    - assets/images/ic_mine_selected.png
    - assets/images/login_logo.png
    - assets/images/lock.png
    - assets/images/account.png
    - assets/images/ic_back_black.png
    - assets/images/ic_back_white.png
    - assets/images/folder_close.png
    - assets/images/folder.png
    - assets/images/folder_open.png
    - assets/images/folder_click_in.png
    - assets/images/img_empty.png
    - assets/images/edit_img.png
    - assets/images/pro_title.png
    - assets/images/click_in_grey.png
    - assets/images/jz_play_normal.png
    - assets/images/img_file_download.png
    - assets/images/file_cad.png
    - assets/images/file_doc.png
    - assets/images/file_excel.png
    - assets/images/file_gis.png
    - assets/images/file_html.png
    - assets/images/file_img.png
    - assets/images/file_music.png
    - assets/images/file_orc.png
    - assets/images/file_pdf.png
    - assets/images/file_ppt.png
    - assets/images/file_txt.png
    - assets/images/file_unknow.png
    - assets/images/file_video.png
    - assets/images/file_zip.png
    - assets/images/img_relation_type.png
    - assets/images/relation_add_blue.png
    - assets/images/relation_search_blue.png
    - assets/images/unknow.png
    - assets/images/bftable_jian.png
    - assets/images/bftable_jia.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
